[package]
publish = false
name = "duralumin-feed"
version.workspace = true
edition.workspace = true

[dependencies]
duralumin-core = { workspace = true }
reqwest        = { workspace = true }
feed-rs        = { workspace = true }
url            = { workspace = true }
thiserror      = { workspace = true }
tracing        = { workspace = true }
