[package]
publish = false
name = "duralumin-metadata"
version.workspace = true
edition.workspace = true

[dependencies]
duralumin-core = { workspace = true }
lofty          = { workspace = true }
chrono         = { workspace = true }
thiserror      = { workspace = true }
tracing        = { workspace = true }
