[package]
publish = false
name = "duralumin-downloader"
version.workspace = true
edition.workspace = true

[dependencies]
duralumin-core = { workspace = true }
reqwest        = { workspace = true }
tokio          = { workspace = true }
sha2           = { workspace = true }
hex            = { workspace = true }
chrono         = { workspace = true }
anyhow         = { workspace = true }
thiserror      = { workspace = true }
tracing        = { workspace = true }
